
const playlistJSON = () => {
 return {
  songs: {
   all_songs: { // done
    title: 'semua list',
    list: [
     "Alan Walker - Alone",
     "Alan Walker - Unity",
     "Alan Walker - On My Way",
     "Alan Walker - Spectre",
     "iLLenium - Takeaway",
     "Maroon5 - Girls Like You",
     "ZAYN - Dusk Till Dawn",
     "Pamungkas - To The Bone",
     "Andra And Backbone - Sempurna",
     "Daun Jatuh - Resah Jadi Luka",
     "Miselia - Akhir Tak bahagia",
     "HONNE - Location Unknown",
     "Olivia Rodrigo - Happier",
     "Alan Waker - All Falls Down",
     "James Arthur - Rewrite The Stars",
     "James A - Say You Won't Let Go",
     "James A - Falling Like The Stars",
     "Billie Eilis & Khalid - Lovely",
     "Tulus - Monokrom",
     "Tulus - Monokrom [Slowed & Reverb]",
     "Tulus - Hati Hati Di Jalan",
     "Tulus - Manusia Kuat",
     "Mitty Zasia - Sesuatu Di Jogja",
     "Last Child - Duka",
     "Virgoun ft.Audy - Selamat Tinggal",
     "Neck Deep - Wish You Were Here",
     "Marsmello - Happier",
     "Cash Cash - Hero",
     "One Republic - Conting Stars",
     "Cash Cash - Take Me Home",
     "Maroon5 - Memories",
     "One Direction - Story Of My Live",
     "BANNERS - Someone to You",
     "Lewis Cipaldi - Someone To You [Slowed Down]",
     "Ava Max - Into Your Arm's",
     "NCS - Heroes To Night",
     "Fat Rat - Well Meet Again",
     "Anne Marie - 2002",
     "Clean Bandit,Demi Lovato - Solo",
     "Runtuh - Feby Putri ft.Fiersa",
     "Billie Elish Feat Khalid - Lovely",
     "Nidji - Laskar Pelangi [Rawi Beat]",
     "Chainsmokers - All We Know",
     "Abdurrahman M - Al Ankabut",
     "Alan Walker - End Of Time",
     "Katy Perry - Unconditional",
     "Demi Lovato - Skyscraper",
     "Ed Sheeran - Beautiful People",
     "Brynn Elliot - Beautiful Things",
     "Gryffin ft.Elley - Tie Me Down",
     "Ed Sheeran - Perfect",
     "Ed Sheeran - Shape Of You",
     "Justin Bieber - Hard2FaceReality",
     "Adele - Easy On Me",
     "Avici - Without You",
     "Loving You is a Losing Game",
     "Jason Derulo - Savage Love",
     "AlifieCastley - Teenage Mona Lisa",
     "James Arthur - Can I Be Him",
     "Demi Lovato - Heart Attack",
     "Rachel Platten - Fight Song",
     "Clean Bandit - Symphony",
     "The Weekend - Save Your Tear",
     "Shawn Mendes - Treat You Better",
     "Rihanna - Diamond",
     "Chard Overstreat - Hold On",
     "Alan Walker - Tired",
     "Abdurrahman M - Al Muzzamil",
     "Avicii - The Night",
     "Glass Animals - Heat Waves",
     "Dean Lewis - Be Alright",
     "Maroon5 - Payphone",
     "NIKI - Every Summertime",
     "Enda - Maafkan aku",
     "R. CITY - Locked Away",
     "Paul Partohap - P.S I Love you",
     "Justin Bieber - Cold Water",
     "Eenie Meenie - Ray & Barron Cov",
     "Keisya Levronka - Tak Ingin Usai",
     "Lewis C - Someone Loved You",
     "RexOrange - THE SHADE",
     "Alfie ft.Aiden - Teenage Monalisa",
     "James Arthur - Say You Won't Let Go [ slowed ]",
     "James Arthur - Can I Be Him? [ slowed ]",
     "James Arthur - Rewrite The Stars [ slowed ]",
     "Last Child - Ketidakrelaanku",
     "Preston Pablo - Flowers Need Rain",
     "Vierra - Seandainya",
     "Rosie Darling - What A Confincing Illusion",
     "Misellia - Akhir Tak Bahagia",
     "Rhianne - Somewhere Only We Know",
     "Selena Gomez - Love You To Love Me",
     "Chloe Adams - She Used To Be Mine",
     "One Direction - Right Now [ Speed Up ]",
     "One Direction - Right Now",
     "Seafret - Atlantis [ Speed Up ]",
     "Jordan Feliz - 180",
     "Brielle Von Hugel - The One That Got Away",
     "One Direction - 18",
     "One Direction - 18 [ Speed Up ]",
     "Babe Rexha x Katy Perry  - Empty X Unconditionally",
     "Babe Rexha - Empty",
     "Taylor Swift - Anti Hero",
     "Hurts So Good - Hurts So Good",
     "Armada - Mabuk Cinta [ Slowed ]",
     "Rizky Febian & Magnolya - Terlukis Indah",
     "Judika - Putus Atau Terus",
     "Maximilian - On My Mind",
     "Justin Bieber ft. Ed Sheeran - I Don't Care",
     "Katharine McPhee - Terrified [ Speed Up ]",
     "Taylor Swift - You Belong With Me",
     "Olivia Rodrigo - All I Want [ Speed Up ]",
     "Cash Cash - Take Me Home",
     "Call Me Karizma - F U Till I F U",
     "The Weekend - After Hours [ Speed Up ]",
     "JJD ft. Cecilia Gault - Vertigo",
     "Last Child For Revenge - Duka X Serana",
     "For Revenge - Serana [ Speed Up ]",
     "Post Malone, Swae Lee - Sunflower",
     "Aruma - Muak",
     "Keisya Levronka - Hidup Tanpamu",
     "Ruth B. - Dendelions",
     "James Arthur - Naked",
     "Ai Huguchi - Aku ma noko",
     "Feby Putri - Halu",
     "Denny Caknan - Kalih Welasku",
     "Cian Ducrot - I'll Be Waiting",
     "Mojiken Studio - A Space For The Unbound",
     "Jason Derulo - Secret Love Song",
     "James Arthur - Cars Outside",
     "Why Don't We - 8 Letters [ Speed Up ]",
     "Gryffin - After You",
     "Keenan Te - Scars",
     "Feby Putri - Kembali Pulang",
     "Guyon Waton X Denny Caknan - Sanes",
     "Denny Caknan - KLEBUS",
     "Illemium, Sasha Sloan - U & Me",
     "Kygo & Selena Gomez - It Ain't Me",
     "Alan Walker - Not You",
     "Denny Caknan X Happy Asmara - Satru",
     "Denny Caknan - Satru 2",
     "Gildcoustic - Nemen [ Speed Up ]",
     "Miqbal Ga ft.Siska Amanda - Dadi Siji",
     "Taylor Swift - Style",
     "Guyonwaton - Korban Janji",
     "Aftershine - Aku Ikhlas",
     "Denny Caknan - Katoyono Medot Janji",
     "Yura Yunita - Dunia Tipu Tipu",
     "Denny Caknan - Gak Pernah Cukup",
     "James Arthur - A Thousand Years",
     "Ghea Indrawati - Jiwa Yang Bersedih",
     "Taylor Swift - Blank Space",
     "Batas Senja - Nanti Kita Seperti Ini",
     "Guyon Waton - Dumes",
     "Jouzu Karakai no Takagi San - Hamabou no hana",
     "James Arthur - A Year Ago",
     "Olivia Rodrigo - Traitor",
     "Justin Bieber - Off My Face",
     "Taylor Swift - Fearless",
     "Taylor Swift - Cruel Summer",
     "Tulus - Jatuh Suka",
     "Noah - Separuh Aku",
     "Tulus - Gajah",
     "Tulus - Labirin",
     "Tulus - Interaksi",
     "Maroon5 - Daylight",
     "Charlie Puth - Left And Right",
     "Oh Wonder - Landslide",
     "Nuu/Shawnii/Xeni - you'll get over it",
     "Woro Widowati - Ikhlas Ngenteni",
     "Taylor Swift - All Of The Girls You Love Before",
     "Siinamota - Young Girl A",
     "Taylor Swift - Love Story",
     "Denny Caknan - Gak Pernah Cukup",
     "James Arthur - A Thousand Years",
     "Ghea Indrawati - Jiwa Yang Bersedih",
     "Taylor Swift - Blank Space","Guyon Waton - Dumes",
     "Hamabou no hana - Hamabou no hana",
     "James Arthur - A Year Ago",
     "Olivia Rodrigo - Traitor",
     "Justin Bieber - Off My Face",
     "Taylor Swift - Fearless",
     "Tulus - Jatuh Suka",
     "Noah - Separuh Aku",
     "Taylor Swift - Cruel Summer",
     "Tulus - Gajah",
     "Tulus - Labirin",
     "Tulus - Interaksi",
     "Charlie Puth - Left And Right",
     "Oh Wonder - Landslide",
     "Nuu/Shawnii/Xeni - you'll get over it",
     "Woro Widowati - Ikhlas Ngenteni",
     "Taylor Swift - All Of The Girls You Love Before",
     "Siinamota - Young Girl A",
     "Taylor Swift - Love Story",
     "Denny Caknan - Gak Pernah Cukup",
     "Arash Buana - We'll Be Okay, For Today",
     "Frawley - If I Don't Laugh, I'll Cry",
     "Nadhif Basalamah - Penjaga Hati",
     "NIKI - lowkey",
     "Troye Sivan - Strawberry And Cigarrates",
     'Frawley - If I Don\'t Laugh, I\'ll Cry',
     'Nadhif Basalamah - Penjaga Hati',
     'NIKI - Lowkey',
     'Piano Peace - Rewrite The Stars (Piano Version)',
     'Bastille - Pompeii (speed up)',
     'Bastille - Pompeii',
     'NIKI - Take A Chance With Me',
     'JP Saxe - If the World Was Ending',
     'Taylor Swift - Slut',
     'Justin Bieber - Intentions',
     'Justin Bieber - As I Am',
     'DJ Khaled - I\'m the One',
     'Rex Orange County - Pluto Projector',
     'Ava Max - Into Your Arms X Alone',
     'Ava Max - Into Your Arms',
     'SZA - Kill Bill',
     'SZA - Open Arms',
     'Eminem - Love The Way You Lie',
     'Justin Bieber - Let Me Love You',
     'Northsle - BUBRAH',
     'Justin Bieber - Sorry',
     'Keenan Te - Scars (Speed Up)',
     'Keenan Te - Scars',
     'Taylor Swift - Foolish One',
     'Boa - Duvet',
     'NIKI - Oceans & Engines',
     'Maroon5 - Animals',
     'Bruno Mars - Marry You',
     'Hal - Terima kasih',
     'SZA - Nobody Gets Me',
     'Chris Andrian - Stay With Me',
     'TXT & Sawano Hiroyuki - Level',
     'Pamungkas - I Love but I\'m Letting Go',
     'Daya - Sit Still, Look Pretty',
     'Tulus - Takkan Terganti',
     'James Arthur - Comeback Kid',
     'Feby Putri - Rantau',
     'Chris Andrian Yang - Until Death Do Us Part',
     'SZA - Saturn',
     'Keenan Te - Forgot About Us',
     'GANGGA - Blue Jeans',
     'Tory Lanez - Say It',
     'Geisha - Sementara Sendiri',
     'Paul Partohap - BEUTiFUL',
     'Aruma - Muak',
     'Zack Tabudlo - Give Me Your Forever',
     'The 1975 - About You',
     'Selena Gomez - Back To You',
     'Caleb Hearn & Rosie - Little Bit Better',
     'Sheila On 7 - Dan...',
     'Charlie Puth - Marvin Gaye',
     'Charlie Puth - We Don\'t Talk Anymore',
     'Charlie Puth - One Call Away',
     'Lauv & Lany - Mean It',
     'Banda Neira - Hujan Di Mimpi',
     'Mighfar Suganda - Gemuruh Riuh',
     'Axwell Ingrosso - More Than You Know',
     'John Legend - All Of Me',
     'Denny Caknan - Wirang',
     'James Arthur - Naked',
     'James Arthur - Losing You',
     'Ichiko Aoba - A hill of the moon',
     'Vanessa Carlton - A Thousand Miles',
     'The Neighbourhood - Sweater Weather',
     'NIKI - La La Lost You',
     'Pendarra - Perjalanan Singkat',
     'Northsle / Agiff - Tresno Liyane',
     'Denny Caknan - Langgeng Dayaning Rasa',
     'Guyon Waton - Gampil',
     'RZD - Yang Kurasa',
     'yaeow/Keenan Te - Favorite Lesson',
     'James Arthur - Bitter Sweet Love',
     'For Revenge - Jakarta Hari Ini',
     'The Weeknd & JENNIE - One Of The Girls',
     '21 Savage / Post Malone - Rockstar'
    ],
    link: ['null'],
   },
   slow_vibes: { // done
    title: 'Slow Vibes',
    list: [
     "Tulus - Monokrom",//
     "Why Don't We - 8 Letters",//
     "Hurts So Good - Hurts So Good [ Slowed ]",//
     "Armada - Mabuk Cinta",//
     "Keenan Te - Scars [ Slowed ]", //
     "James Arthur - Cars Outside [ Slowed ]",//
     "James Arthur - A Year Ago [ Acoustic ]",//
     "NIKI - lowkey",//
     "Judika - Putus Atau Terus",//
     "Mitty Zasia - Kusut",//
     "Rosa Lim - Snap",//
     "Aruma - Muak",//
     "Pamungkas - To The Bone",//
     "Andra And Backbone - Sempurna",//
     "Keisya Levronka - Hidup Tanpamu",//
     "Mitty Zasia - Sesuatu Di Jogja",//
     "Selena Gomez - Love You To Love Me",//
     "James Arthur - Can I Be Him? [ slowed ]",//
     "Billie Eilis & Khalid - Lovely",//
     "Joji - Glimpse of Us",//
    ],
    link: [
     "https://open.spotify.com/track/4GfK1qOF3uBWidbPlTCQRL?si=EbZ5wYigS12Wz60VWcj19w",
     "https://open.spotify.com/track/4zRZAmBQP8vhNPf9i9opXt?si=WZP62esSSjSxXHuBfbrvcw",
     "https://open.spotify.com/track/7pQ1Gr4h79lVBc0ER4YUVK?si=jeb1oj5XTyW1V2k2UrMuiw",
     "https://open.spotify.com/track/7gWcfdZVM1uunqG6trmQVG?si=Yz853S5dTCKJLmpKP5iT6Q",
     "https://open.spotify.com/track/2OUR6eaINRdJJAWzY9ooGP?si=zA2pkYuWRauM8DjBfqWAfg",
     "https://open.spotify.com/track/1INBzhPNmE5956Vz0OpWAV?si=AfJL1rMcSBSlVdw6r9_l5A",
     "https://open.spotify.com/track/1J5Ne35kjDK1babqq9AsUc?si=TSwr418-SB2hFZ6kTfoQDQ",
     "https://open.spotify.com/track/7ipqVwkp2MhZv0Ojzqy1NV?si=aA60v2ggRUGwk1JvSzxw_w",
     "https://open.spotify.com/track/7HBW6yX8iRf81nn6NVOzHL?si=4Qhv3DNxRwOevZlZKhP7CQ",
     "https://open.spotify.com/track/0301DpIhbVSPDWceTO8i8I?si=1jaImHKOSrW0gR5OdvO8nQ",
     "https://open.spotify.com/track/5hx7w26Zi3zafMgvMTUqF6?si=KyVSS0c0RfiFdtQ10y0bXg",
     "https://open.spotify.com/track/3N2WeXxSjngB1DSi8vrI8C?si=7_0TvqGpTUW3dl9PoMynIQ",
     "https://open.spotify.com/track/3pCt2wRdBDa2kCisIdHWgF?si=pL1cUbDlTGmKricRPqs9Yg",
     "https://open.spotify.com/track/2UgCs0i0rNHUH2jKE5NZHE?si=e-6gVWvBQq2XolHDq-ppWQ",
     "https://open.spotify.com/track/04VEB5LZ6slykz3tXTmYpY?si=2U93vTJ-Tb-P53QdhAEQgw",
     "https://open.spotify.com/track/0oHKzdjG6EWE9ENqfwslOf?si=4vGY9jJeS9mZbi_tOmu4Qw",
     "https://open.spotify.com/track/4l0Mvzj72xxOpRrp6h8nHi?si=WyoGnrLuRuWx9XS-7rZqsQ",
     "https://open.spotify.com/track/0VhgEqMTNZwYL1ARDLLNCX?si=GmfpQRALQH-N28NL9yDHbw",
     "https://open.spotify.com/track/0u2P5u6lvoDfwTYjAADbn4?si=OfDsPSR9TX-JgjFI3YjIQQ%0A",
     "https://open.spotify.com/track/6xGruZOHLs39ZbVccQTuPZ?si=Hdk16-2sRZ2MPBYqxxfM9g",
    ],
   },
   speed_vibes: { // done
    title: 'Speed Vibes',
    list: [
    "One Republic - Conting Stars", //
    "Cash Cash - Take Me Home",//
    "Tulus - Labirin",//
    "Maroon5 - Daylight",//
    "Maroon5 - Memories",//
    "Maroon5 - Girls Like You",//
    "One Direction - Story Of My Live",//
    "Taylor Swift - Cruel Summer",//
    "Demi Lovato - Heart Attack",//
    "R. CITY - Locked Away",//
    "Ed Sheeran - Happier",//
    "Last Child - Ketidakrelaanku",//
    "Rosa Lim - Snap [ Speed Up ]",//
    "One Direction - Right Now [ Speed Up ]",//
    "Seafret - Atlantis [ Speed Up ]",//
    "Justin Bieber ft. Ed Sheeran - I Don't Care",//
    "Katharine McPhee - Terrified [ Speed Up ]",//
    "Taylor Swift - You Belong With Me",//
    "Call Me Karizma - F U Till I F U",//
    "The Weekend - After Hours [ Speed Up ]",//
    "Jason Derulo - Secret Love Song",//
    "Keenan Te - Scars",//
    "Taylor Swift - Style",//
    "JJD ft. Cecilia Gault - Vertigo",//
    "For Revenge - Serana [ Speed Up ]",//
    "Olivia Rodrigo - All I Want [ Speed Up ]"//
    ],
    link: [
     "https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1?si=MrBQujngS0i8EkXp_d1leg",
     "https://open.spotify.com/track/3j9AY9emI5H45iMxTpT4TJ?si=9AieFFVHSx6epZPvfqHSAQ",
     "https://open.spotify.com/track/0pDmW5AOpl1Wi58Ob0xXB8?si=rd01J3u6Sqei_NIX0vXYxA",
     "https://open.spotify.com/track/1NNAI51EuoRWw1ydX1zV7S?si=Tht2jrrkSyCQCWgF33v6kg",
     "https://open.spotify.com/track/4cktbXiXOapiLBMprHFErI?si=JUJBDyaqQUmxLD2vkGgr4w",
     "https://open.spotify.com/track/7fa9MBXhVfQ8P8Df9OEbD8?si=dlEn4bBeQTOmpULdhEDPqQ",
     "https://open.spotify.com/track/4nVBt6MZDDP6tRVdQTgxJg?si=OipiSPf0THySdtrMCODIxw",
     "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr?si=VauoG9ufReGHJgTypBjOow",
     "https://open.spotify.com/track/1V6gIisPpYqgFeWbMLI0bA?si=pyA2jMlAQH--3BfKH4N3KQ",
     "https://open.spotify.com/track/7x5xYW5W42OGPAdHUyyguy?si=AMarq5tVQ4u7beOwaxpvSg",
     "https://open.spotify.com/track/2RttW7RAu5nOAfq6YFvApB?si=PBSzq7yRQOCGMMCDoO7TKw",
     "https://open.spotify.com/track/6Es0DuLXDpFPkq6QDR5BvP?si=_ooxKM1bS2a_caOWtxR-0g",
     "https://open.spotify.com/track/1VTqkUQpj29vAUZ8br5fB0?si=4AKWcDfuR9yT5XSFs4Yt5Q",
     "https://open.spotify.com/track/1dQQ2QlnvXUehsRUrukKmf?si=lWYXWymJSWCFNd5y5_Ydfg",
     "https://open.spotify.com/track/72VBmMUTEVWFcDUVgMbqo0?si=l0OeF2XJTl-cHxdg4OygWg",
     "https://open.spotify.com/track/3HVWdVOQ0ZA45FuZGSfvns?si=UZiw7z7KQdSNOHburiQezg",
     "https://open.spotify.com/track/2tUWRIPPYfEjLMCVnYmNHp?si=cwH14k0rTnCPPTuYuA8Kjg",
     "https://open.spotify.com/track/1qrpoAMXodY6895hGKoUpA?si=b9J1frkZQbmCiXpEcsxJBw",
     "https://open.spotify.com/track/43W8zo8ohchliMXL2br1v9?si=baoWa2YeSH28-fTxq3rr3w",
     "https://open.spotify.com/track/2cm1JoL43kP9BbTXPxKirZ?si=d45PNMgmSbmN6ZHwOVHg5g",
     "https://open.spotify.com/track/6KHL1En9v6iNWjcs44mcmU?si=o0kxg8SWQxWgrqOtyb8XmA",
     "https://open.spotify.com/track/5SjfjoYaRJ5jycgqwV0ow0?si=1rAUTjRcRo6GPyWkS65MJw",
     "https://open.spotify.com/track/0ug5NqcwcFR2xrfTkc7k8e?si=4HmjaVl-QhiFXSXnDcLGZg",
     "https://open.spotify.com/track/0Ptbg3nbvmHK5AMQ2OQxvV?si=T1WcseG9Txuci4Rfy662OQ",
     "https://open.spotify.com/track/4woh8bmJViP9hmiXz8LVA8?si=POBcjntHS3irH0wk4ju-sg",
    ],
   },
   sad_vibes: { // done
    title: 'Sad Vibes',
    list: [
     "Feby Putri Ft. Fiersa Besari - Runtuh",
     "Daun Jatuh - Resah Jadi Luka",
     "Miselia - Akhir Tak bahagia",
     "Keisya Levronka - Tak Ingin Usai",
     "Last Child - Duka",
     "Virgoun ft.Audy - Selamat Tinggal",
     "Vierra - Seandainya",
     "Feby Putri - Usik",
     "Feby Putri - Halu",
     "Noah - Separuh Aku",
     "Judika - Putus Atau Terus",
     "Nadhif Basalamah - Penjaga Hati",
     "Ghea Indrawati - Jiwa Yang Bersedih"
    ],
    link: [
     "https://open.spotify.com/track/6Hii26x3qDErVitnGW8QtO?si=V_8D4OeuT5ijeyNRzCHAVg",
     "https://open.spotify.com/track/2sULdMKWdBdK2ZtntuFvSb?si=pKHTVu2dS8-kGzL0siDz7A",
     "https://open.spotify.com/track/0BYoWATcndOBcsCfKdTKRx?si=4dgGvcStTP6W_GIDenxPhw",
     "https://open.spotify.com/track/1b0aDgrG775i4sPQgJGmkU?si=Wnl0-8aXQSWhBItrhGS8NQ",
     "https://open.spotify.com/track/5MIpcd16T59wFeqAChSYwC?si=lI9YnjtfSQqdRhqoW2hKug",
     "https://open.spotify.com/track/1mruWrUwAVe2XkksUQiaHK?si=yqkcPwR0SI6_zYwjl2Elkw",
     "https://open.spotify.com/track/5NmjnghJGJRFg34KGGx8O0?si=ePwbdztrQw24dUMWy80TRA",
     "https://open.spotify.com/track/0301DpIhbVSPDWceTO8i8I?si=cmIv0BBBSLCUx7YkeA8YvQ",
     "https://open.spotify.com/track/3iszMeG87RxYujbKieNNRQ?si=k4DIRiZBSwuWRl5XR1vebw",
     "https://open.spotify.com/track/4sJmv194lQKWjytpaxH1Vj?si=bTmqLCmcS3-ZtEwYUf9aRw",
     "https://open.spotify.com/track/7F4tV8SiUy6itZTdAzdafO?si=P0Xz3UjfTaaKd0OPiDyaaA",
     "https://open.spotify.com/track/6XsFgTG4dY768oIB4Dmeu0?si=8kTKIWPwQ2KfERZM_pIx9g",
     'https://open.spotify.com/track/6XsFgTG4dY768oIB4Dmeu0?si=-bH9KQ3iSpC77ULXtToFkw'
    ],
   },
   happy_vibes: { // done
    title: 'Happy Vibes',
    list: [
      'Charlie Puth - We Don\'t Talk Anymore',//
      'Charlie Puth - Marvin Gaye',//
      'Charlie Puth - One Call Away',//
      'Lauv & Lany - Mean It',//
      'Chris Andrian - Stay With Me',//
      "Taylor Swift - Cruel Summer",//
      "Taylor Swift - Style",//
      "Tulus - Gajah",//
      "Tulus - Labirin",//
      "Tulus - Interaksi",//
      "Taylor Swift - Love Story",//
      "Maroon5 - Daylight",//
      "Charlie Puth - Left And Right",//
      "Ruth B. - Dendelions",//
      "Taylor Swift - You Belong With Me",//
      "Taylor Swift - Anti Hero",//
      "RexOrange - THE SHADE",//
      "Eenie Meenie - Ray & Barron Cov",//
      "R. CITY - Locked Away",//
      "Ed Sheeran - Happier",//
      "Maroon5 - Payphone",//
      "Avicii - The Night",//
      "Shawn Mendes - Treat You Better",//
      "Rihanna - Diamond",//
      "Dylan Brady - Still Into You",//
      "Mitty Zasia - Sesuatu Di Jogja",//
      "Jason Derulo - Savage Love",//
      "Gryffin ft.Elley - Tie Me Down",//
      "Ed Sheeran - Perfect",//
      "Clean Bandit,Demi Lovato - Solo",//
      "Anne Marie - 2002",//
      "One Direction - Story Of My Live",//
      "Alan Walker - Spectre",//
      "BANNERS - Someone to You",
      "Marsmello - Happier",
      "Cash Cash - Hero",
      "Maroon5 - Girls Like You",
    ],
    link: [
     "https://open.spotify.com/track/06KyNuuMOX1ROXRhj787tj?si=3qCgz7NdSvmNP-Kenw_wkA",
     "https://open.spotify.com/track/3rKYiySCDMUKTw5kGVVhaa?si=RQ4CYkpwTou5tVw-UxvVKg",
     "https://open.spotify.com/track/37R0bQOQj5a7DOqh1TGzvB?si=w4d7avb8SSWLN9jWvZmniA",
     "https://open.spotify.com/track/6mXdCcFnPKQznj4CmMRmHC?si=0qMq3xZtRtK1DHXfG4norQ",
     "https://open.spotify.com/track/6EgwlXnFrfkFqOKqY3dqki?si=C3IxKscdQ462rW2TI24jmA",
     "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr?si=edVPI0hvTryDI_CyHizu7A",
     "https://open.spotify.com/track/0ug5NqcwcFR2xrfTkc7k8e?si=5d4vqcDSSpy-eavdtnTvFw",
     "https://open.spotify.com/track/7vZTvo2aJ6wHKCGjwjdWIf?si=B9eHjwUlRvCBpv8eUIvDLg",
     "https://open.spotify.com/track/0pDmW5AOpl1Wi58Ob0xXB8?si=MvXRxLG-RbeOLRXPSkHKWA",
     "https://open.spotify.com/track/32Pdf9eyXDEMoClEJW6yYP?si=7LFpnHeBQKuACZqdTeV8pA",
     "https://open.spotify.com/track/3CeCwYWvdfXbZLXFhBrbnf?si=7xL6Q--aSPqsG2VZ3HlLbw",
     "https://open.spotify.com/track/1fzAuUVbzlhZ1lJAx9PtY6?si=hhPhE-IJQeSkQh8iRNDgfw",
     "https://open.spotify.com/track/5Odq8ohlgIbQKMZivbWkEo?si=6Vnsm7-zR_eF2yFhJTTe9g",
     "https://open.spotify.com/track/2eAvDnpXP5W0cVtiI0PUxV?si=oc0rV25TQ06yDL3uDSu_yA",
     "https://open.spotify.com/track/1qrpoAMXodY6895hGKoUpA?si=LF64Yjj0Sr2JYVJrbKDCew",
     "https://open.spotify.com/track/0V3wPSX9ygBnCm8psDIegu?si=mcgyxJs6R_OjsW9Sngechg",
     "https://open.spotify.com/track/1gH1h30wkQdd9zhY3j7a8T?si=Vyu2-UsoQrGg8zkuuWrhnw",
     "https://open.spotify.com/track/4vVTI94F9uJ8lHNDWKv0i2?si=PbBt2X6dSFiSUoAuEt9UAQ",
     "https://open.spotify.com/track/7x5xYW5W42OGPAdHUyyguy?si=1A7f-VYoTtKx_MQ5cw2XnA",
     "https://open.spotify.com/track/2RttW7RAu5nOAfq6YFvApB?si=AMgjH9UbRT-n4171cP2uKg",
     "https://open.spotify.com/track/1XGmzt0PVuFgQYYnV2It7A?si=esl1iXOCRwaw21WtieoS2w",
     "https://open.spotify.com/track/0ct6r3EGTcMLPtrXHDvVjc?si=WyCUe_y0Sr-GdKSBbl9erg",
     "https://open.spotify.com/track/3QGsuHI8jO1Rx4JWLUh9jd?si=cf7po0QkR-OJQOVK3YZYEA",
     "https://open.spotify.com/track/65YsalQBmQCzIPaay72CzQ?si=82P5S09VSSGv34gwnrvOsw",
     "https://open.spotify.com/track/1yjY7rpaAQvKwpdUliHx0d?si=2flcVr2rQ72PMuSqRFnHQg",
     "https://open.spotify.com/track/0oHKzdjG6EWE9ENqfwslOf?si=0GMb403YScijY0pdCpUFcw",
     "https://open.spotify.com/track/1xQ6trAsedVPCdbtDAmk0c?si=yqlkTQyhSjurFqeyfyaufw",
     "https://open.spotify.com/track/2zh01m4PiHaZz4BAm0NRxs?si=GrITVyt0Q7e3ZMsa59g1Lw",
     "https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v?si=winImgqORv6YyB786j0u-w",
     "https://open.spotify.com/track/3NuK5xMlSlB6K2Qp16zf3h?si=bEk-KERRR_-i5VF3bUqxuQ",
     "https://open.spotify.com/track/2BgEsaKNfHUdlh97KmvFyo?si=gVh85E5STFy1PbX7zHRjhQ",
     "https://open.spotify.com/track/4nVBt6MZDDP6tRVdQTgxJg?si=dUwgeThfRh-rJVAO87rFWQ",
     "https://open.spotify.com/track/2DGa7iaidT5s0qnINlwMjJ?si=QFw-eTIrQ0KSScG3f6KW7Q",
     "https://open.spotify.com/track/14BH4qO7pgCmIe6mgLKOK3?si=6_WF0rGHQlG0k7L8zEw76g",
     "https://open.spotify.com/track/7BqHUALzNBTanL6OvsqmC1?si=ZqX7pZoSRwyNKFZdjlgEIw",
     "https://open.spotify.com/track/5g1BARk25uUJtEPSUwcjnU?si=aIV8i63zRJWXq5QCxGiaHQ",
     "https://open.spotify.com/track/7fa9MBXhVfQ8P8Df9OEbD8?si=UIswgfMySLu60IMETMSoRw",
    ],
   },
   chill_vibes: { // done
    title: 'Chill Vibes',
    list: [
     "Alan Walker - Alone",//
     "Alan Walker - Unity",//
     "Alan Walker - On My Way",//
     "Alan Walker - Spectre",//
     "Alan Walker - Lily",//
     "iLLenium - Takeaway",//
     "Maroon5 - Girls Like You",//
     "ZAYN - Dusk Till Dawn",//
     "Pamungkas - To The Bone",//
     "Andra And Backbone - Sempurna",//
     "Daun Jatuh - Resah Jadi Luka",//
     "Miselia - Akhir Tak bahagia",//
     "HONNE - Location Unknown",//
     "Olivia Rodrigo - Happier",//
     "Alan Waker - All Falls Down",//
     "James Arthur - Rewrite The Stars",//
     "James A - Say You Won't Let Go",//
     "James A - Falling Like The Stars",
     "Billie Eilis & Khalid - Lovely",
     "Tulus - Monokrom",
     "Tulus - Hati Hati Di Jalan",
     "Tulus - Manusia Kuat",
     "Mitty Zasia - Sesuatu Di Jogja",
     "Last Child - Duka",
     "Virgoun ft.Audy - Selamat Tinggal",
     "Neck Deep - Wish You Were Here",
     "Tulus - Jatuh Suka",
     "Noah - Separuh Aku",
     "Yuji Ft.Putri Dahlia - Old Love",
     "Raissa Anggiani - Lagi Lagi",
     "Mitty Zasia - Kusut",
     "Tulus - Nala",
     "Raissa Anggiani - Kau Rumahku",
     "Tulus - Pamit",
     "Tulus - Diri",
     "Tulus - Gajah",
     "One Direction - Night Changes",
     "Dere - Kota",
     "Troye Sivan - Angel Baby",
     "Dylan Brady - Still Into You",
     "Avicii - The Night Cv.Chlara",
     "Feby Putri - Usik",
     "Feby Putri - Liar Angin",
    ],
    link: [
     "https://open.spotify.com/track/3LlmKSHR3Rs0Y3KHQLAYDk?si=Z3ddOPmpTs2fAuz_SZsNvA",
     "https://open.spotify.com/track/3Os9onUOoxT6EP3kwiMRKA?si=G7OOMgEjRImFM0LGnty2Lw",
     "https://open.spotify.com/track/4n7jnSxVLd8QioibtTDBDq?si=U0gbstYsQl-jlS1iNo_H7Q",
     "https://open.spotify.com/track/2DGa7iaidT5s0qnINlwMjJ?si=PlwJsKfUTLOMcL0CJjJnEg",
     "https://open.spotify.com/track/0lks2Kt9veMOFEAPN0fsqN?si=Y3QEs5PES2ybljcGmythsg",
     "https://open.spotify.com/track/3g0mEQx3NTanacLseoP0Gw?si=nGWeJaTHQZWl35F7qNIdWQ",
     "https://open.spotify.com/track/7fa9MBXhVfQ8P8Df9OEbD8?si=-lWUFtAkQlSo5_D_-wM2Jw",
     "https://open.spotify.com/track/3e7sxremeOE3wTySiOhGiP?si=OVsB3IR5Sj6MriEO9hxatQ",
     "https://open.spotify.com/track/3pCt2wRdBDa2kCisIdHWgF?si=HDamkNneRceBYNZ7ZJc3sw",
     "https://open.spotify.com/track/2UgCs0i0rNHUH2jKE5NZHE?si=zbaytNXhQv6mMDHM3DOZnA",
     "https://open.spotify.com/track/2sULdMKWdBdK2ZtntuFvSb?si=UZ2xHrdWQm2pbyNjopflVQ",
     "https://open.spotify.com/track/0BYoWATcndOBcsCfKdTKRx?si=uy69lDXMQ8ullcUtyooplw",
     "https://open.spotify.com/track/43kiDtoYD0nDJYxzQwclpT?si=eflHcWzATCG1-UnMh1z3HQ",
     "https://open.spotify.com/track/2tGvwE8GcFKwNdAXMnlbfl?si=Pj-ruRHARfOErOzzR7oZZw",
     "https://open.spotify.com/track/5yFSF6qQA1rcLsQRnBsZgb?si=sgZkWittSta__gk6B-nL2Q",
     "https://open.spotify.com/track/7FlHNJT4TC120CDvFOHzei?si=F3XWrWX9QMS_abHmyH4_Aw",
     "https://open.spotify.com/track/5uCax9HTNlzGybIStD3vDh?si=tSUCv_jwQHCM5-DGg4kBcQ",
     "https://open.spotify.com/track/395KzBy0bkb57dEvg6cfzJ?si=FCK_fg_tT3ChpPqoy8h_hw",
     "https://open.spotify.com/track/0u2P5u6lvoDfwTYjAADbn4?si=1xoUzt9lRKC2jYKeCAkizg",
     "https://open.spotify.com/track/4GfK1qOF3uBWidbPlTCQRL?si=NnSPfLNhQoS0vVYtAT0fBQ",
     "https://open.spotify.com/track/2hHeGD57S0BcopfVcmehdl?si=CF3bSnDSS7awx0qzGOmScw",
     "https://open.spotify.com/track/1vT1rKlEzvT9r0uYwAuwC8?si=DzwnhyA3TOCUWLUhgESKag",
     "https://open.spotify.com/track/0oHKzdjG6EWE9ENqfwslOf?si=JNVFQcx3SgeRnXuhK6xUMQ",
     "https://open.spotify.com/track/5MIpcd16T59wFeqAChSYwC?si=XF0dxdfJTj-ek2kLCRsqeA",
     "https://open.spotify.com/track/1mruWrUwAVe2XkksUQiaHK?si=TKVSE4MvRhGJd0vjc_lm9Q",
     "https://open.spotify.com/track/4Ssi6tKwrTHi5qvDndrZRP?si=_Z_c8lzDTJGHXAfR2HysSQ",
     "https://open.spotify.com/track/6PqWdGIYq5xdLaa4zCZfRp?si=MCARm9HdQJmYinvBtn2Fxg",
     "https://open.spotify.com/track/4BDA2HN9dQtrXjk8b6zaTq?si=IFUAQ7ARQOuzYl3GQyND4Q",
     "https://open.spotify.com/track/3W4U7TEgILGpq0EmquurtH?si=qbdSU9ceTY6JY_6KwEvkCQ",
     "https://open.spotify.com/track/2kN0Lv2Bk0n1KuP9drjWxf?si=Ay9QiztbR3Gr-yZRq95fow",
     "https://open.spotify.com/track/3diD8b3u6oEn74BezQpujj?si=1fC9ZVs8QaG7hCXgFriw5g",
     "https://open.spotify.com/track/3AdEZRmsa3zviTr2Whx3zI?si=04bsYGPWQBuBAfjI0PttAQ",
     "https://open.spotify.com/track/7nQoDLkzCcoIpKPQt3eCdN?si=JDXTSatGR0u13rWMhqQXVw",
     "https://open.spotify.com/track/3B4VP6swG49n3scg2aMfA6?si=P2yvcpYFShy7jakyhHeGvw",
     "https://open.spotify.com/track/2qgjqbi96IAOBzZFC6H57U?si=1xHaIgXdSCSp7dKj6dXaCg",
     "https://open.spotify.com/track/7vZTvo2aJ6wHKCGjwjdWIf?si=EisU9Ec5TR-jvBJnOZgYiA",
     "https://open.spotify.com/track/5O2P9iiztwhomNh8xkR9lJ?si=O498aoieTxmQlvGUVbaKkg",
     "https://open.spotify.com/track/0SeBJ2sAl8CV58kBfpd5va?si=alevKyNYT3Ophn9e9p_gKw",
     "https://open.spotify.com/track/3wlLknnMtD8yZ0pCtCeeK4?si=KR4X55WSQpmBxh3bQjUMWA",
     "https://open.spotify.com/track/1yjY7rpaAQvKwpdUliHx0d?si=JoKQS_rdRgKxXF7uYfI2jA",
     "https://open.spotify.com/track/3YkhNMK7YcdkUSKM5nM3ur?si=o0b8LEd9T2Kp-Jj4h7HyLg&context=spotify%3Aalbum%3A3HB8IlJuG0cOxpp77kJdwx",
     "https://open.spotify.com/track/0301DpIhbVSPDWceTO8i8I?si=khbFRaB_Sk2CheqEGht1fw",
     "https://open.spotify.com/track/3i1l8aRJWIl9cwuEHSiVar?si=vlOBjw45R369Mp9SbV8_6A",
    ],
   },
   study_vibes: { // done
    title: 'Study Vibes',
    list: [
     "Tulus - Monokrom",
     "Oh Wonder - Landslide",
     "NIKI - Lowkey",
     "JP Saxe - If the World Was Ending",
     "Ichiko Aoba - A Hill of the Moon",
     "James Arthur - Naked",
     "The Neighbourhood - Sweater Weather",
     "Rex Orange County - Pluto Projector",
     "Pamungkas - I Love You but I'm Letting Go",
     "Paul Partohap - P.S I Love You",
     "Yuji Ft.Putri Dahlia - Old Love",
     "Tulus - Gajah",
     "Dean Lewis - Be Alright",
     "Rosie Darling - What A Convincing Illusion",
     "Adele - Easy On Me",
     "Feby Putri - Halu",
     "Taylor Swift - Love Story",
     "John Legend - All of Me",
     "SZA - Saturn",
     "Bruno Mars - Marry You",
     "NIKI - Oceans & Engines",
     "Maroon5 - Memories",
     "James Arthur - Say You Won't Let Go",
     "Lewis Capaldi - Someone You Loved",
     "Selena Gomez - Back To You",
     "Tulus - Jatuh Suka",
     "Charlie Puth - We Don’t Talk Anymore",
     "James Arthur - Bitter Sweet Love"
    ],
    link: [
     "https://open.spotify.com/track/4GfK1qOF3uBWidbPlTCQRL?si=978aD3pSRbKI5DmKi7Q1Kg",
     "https://open.spotify.com/track/3X3mfRMRaPJRiIMDMQtSkd?si=aZASht7mRFWYZZ6DMQwxRw",
     "https://open.spotify.com/track/7ipqVwkp2MhZv0Ojzqy1NV?si=sUDa9IBdSGaOVvJ-Eqz3ng",
     "https://open.spotify.com/track/77MdvMx9L4ZQuLhhn3o21h?si=WLXopfMfTKaiJNE6mPUFIg",
     "https://open.spotify.com/track/79TkZmpXpNxLDi1RL0AXhP?si=p3u9U9_rSEm6mQrGSXS_xg",
     "https://open.spotify.com/track/2fmyrECK6bdfoGven0UMZx?si=-6P6IT52ShKMDRa2t3jkdw",
     "https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6?si=ptbR_F5oSBe036Jx0VomIA",
     "https://open.spotify.com/track/4EWBhKf1fOFnyMtUzACXEc?si=MdAFBaECS-eMUlNPkWh9Zg",
     "https://open.spotify.com/track/01beCqR9wsVnwzkAJZyTqq?si=v7UEme8qSYmHeO4d3g7-EA",
     "https://open.spotify.com/track/1w3azB0VuRFp79AduIwrIy?si=oUXd6hm0TUSUm-IEnav5LQ",
     "https://open.spotify.com/track/3W4U7TEgILGpq0EmquurtH?si=95jFprEkRaO9VZla-9jsxw",
     "https://open.spotify.com/track/7x72y8x4Xwe0H1IVd6qD2y?si=G_LdRDJnSjiiEymZ8niPhQ",
     "https://open.spotify.com/track/3EPXxR3ImUwfayaurPi3cm?si=QNrz8ZrPTsilmTU7R_ZufA",
     "https://open.spotify.com/track/0xErGPogrWKGjWI1bEMLaV?si=A1zSPAOIRuuMOEbKuRgeew",
     "https://open.spotify.com/track/0gplL1WMoJ6iYaPgMCL0gX?si=kmf1aZV5QFuKQDxQIt3ObA",
     "https://open.spotify.com/track/3iszMeG87RxYujbKieNNRQ?si=2yNkfoyZT4WskUXVb4UYrg",
     "https://open.spotify.com/track/3CeCwYWvdfXbZLXFhBrbnf?si=bLuBYTyNRHm8LjmBHZBjEw",
     "https://open.spotify.com/track/3U4isOIWM3VvDubwSI3y7a?si=03VyE27nRky6snhoSJ5V4g",
     "https://open.spotify.com/track/1bjeWoagtHmUKputLVyDxQ?si=3YGH_o0MRXKSVH75h2x-Bw",
     "https://open.spotify.com/track/6SKwQghsR8AISlxhcwyA9R?si=zRjbtkImRgqU3VdSKKvaaA",
     "https://open.spotify.com/track/3vZk7OAUjMtVDNC852aNqi?si=egyDU_1kSA2M1Tlmoj7q3Q",
     "https://open.spotify.com/track/4cktbXiXOapiLBMprHFErI?si=SpkZoiA2S8qZ5O4QR5_m2A",
     "https://open.spotify.com/track/5uCax9HTNlzGybIStD3vDh?si=hqODLifTT0eSSWqxEaemIg",
     "https://open.spotify.com/track/7qEHsqek33rTcFNT9PFqLf?si=W_Ltp6euSpOciJ0oykTSvA",
     "https://open.spotify.com/track/514rhnksEwHUh6LxXsQ4Y9?si=AF4y6sKUQfORtNspSA-kqw",
     "https://open.spotify.com/track/6PqWdGIYq5xdLaa4zCZfRp?si=n8L47R5DRmq_dmf__xIVJA",
     "https://open.spotify.com/track/06KyNuuMOX1ROXRhj787tj?si=ri5dxFibSQ2sluTa8qLx3Q",
     "https://open.spotify.com/track/3ypPLl97oKAhbx0vfbSDoi?si=a0oZ1VOERz2lR_L4aBoN5g",
    ],
   },
   productive_vibes: { // done
    title: 'Productive Vibes',
    list: [
     "Alan Walker - Spectre",
     "Maroon5 - Daylight",
     "Clean Bandit, Demi Lovato - Solo",
     "Avicii - The Nights",
     "Ava Max - Into Your Arms",
     "The Weeknd - Save Your Tears",
     "James Arthur - Rewrite The Stars",
     "Shawn Mendes - Treat You Better",
     "Why Don't We - 8 Letters",
     "OneRepublic - Counting Stars",
     "Taylor Swift - Blank Space",
     "Katy Perry - Unconditionally",
     "Chainsmokers - All We Know",
     "Gryffin ft. Elley - Tie Me Down",
     "Taylor Swift - Cruel Summer",
     "Maroon 5 - Payphone",
     "Marshmello - Happier",
     "Cash Cash - Take Me Home",
     "The 1975 - About You",
     "Troye Sivan - Strawberries & Cigarettes",
     "Justin Bieber - Sorry"
    ],
    link: [
     "https://open.spotify.com/track/2DGa7iaidT5s0qnINlwMjJ?si=UjCpUjovQ0C_M8pV8ygYPQ",
     "https://open.spotify.com/track/1NNAI51EuoRWw1ydX1zV7S?si=409RueTUTD6fPX9csyugVA",
     "https://open.spotify.com/track/3NuK5xMlSlB6K2Qp16zf3h?si=YRwYcbGYRJ6okUWzOBGWmg",
     "https://open.spotify.com/track/0ct6r3EGTcMLPtrXHDvVjc?si=SxPYtFTUQT288hyvvDSnAQ",
     "https://open.spotify.com/track/0b11D9D0hMOYCIMN3OKreM?si=3X4u7ampR8iPYAjoJe0z7g",
     "https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g?si=bI9UezdjRJ6uuYw8_B2NoQ",
     "https://open.spotify.com/track/7FlHNJT4TC120CDvFOHzei?si=Ic8DfUIdQyyCCvjAF-2D1w",
     "https://open.spotify.com/track/3QGsuHI8jO1Rx4JWLUh9jd?si=iWXKvu5BQ3CZZzoTSu1n6w",
     "https://open.spotify.com/track/4zRZAmBQP8vhNPf9i9opXt?si=iHUeA9WRS7KPKxly4O4Gkg",
     "https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1?si=blw7X_m_TzOVcQr1aOhaYw",
     "https://open.spotify.com/track/1u8c2t2Cy7UBoG4ArRcF5g?si=V526c1NXTuyyqkJUygpXAg",
     "https://open.spotify.com/track/009ImBOrIUlWgla8U05RAC?si=juH2eljpRr-ChnES3esmOQ",
     "https://open.spotify.com/track/2rizacJSyD9S1IQUxUxnsK?si=S1FSr7cUSouiFjYLzwCpKg",
     "https://open.spotify.com/track/2zh01m4PiHaZz4BAm0NRxs?si=ls1vEvbrTvqCx5_JkjNQpA",
     "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr?si=NSkMTwALQlyfMduqFc0Ocw",
     "https://open.spotify.com/track/1XGmzt0PVuFgQYYnV2It7A?si=pO6Wb7wUQxyf-qZMvQtm2Q",
     "https://open.spotify.com/track/7BqHUALzNBTanL6OvsqmC1?si=zrUEGOyJSg6t2Q_7y676rw",
     "https://open.spotify.com/track/7L59vVTpoS94JU3KEeolqt?si=8RSIv77ASb2B4Btm7avVVg",
     "https://open.spotify.com/track/1fDFHXcykq4iw8Gg7s5hG9?si=AqCGHLLvT1qcfLqnhZzqMg",
     "https://open.spotify.com/track/3afkJSKX0EAMsJXTZnDXXJ?si=Bh3rLdRnS8OB7IGfcx8dxA",
     "https://open.spotify.com/track/0JBq4P9Jpp37F1PteCgGL1?si=4MxkY69BRnWF90k6k6KrBw",
    ],
   },
   jawa_vibes: { // done
    title: 'Jawa Vibes',
    list: [
     "Denny Caknan - Satru 2",
     "Guyon Waton - Korban Janji",
     "Denny Caknan - Klebus",
     "Guyon Waton - Dumes",
     "Denny Caknan - Gak Pernah Cukup",
     "Guyon Waton - Gampil",
     "Denny Caknan - Sigar",
     "Woro Widowati - Ikhlas Ngenteni",
     "Denny Caknan - Langgeng Dayaning Rasa",
     "Miqbal Ga ft. Siska Amanda - Dadi Siji",
     "Denny Caknan - Katonyo Medot Janji",
     "Denny Caknan X Happy Asmara - Satru",
     "Denny Caknan - Wirang",
     'Northsle - BUBRAH',
     "Guyon Waton - Pingal",
     "Aftershine - Aku Ikhlas",
     "Northsle - Tresno Liyane",
     "Guyon Waton X Denny Caknan - Sanes",
     "Gildcoustic - Nemen",
     "Vadesta Ft.Destya Eka - Saktenane"
    ],
    link: [
     "https://open.spotify.com/track/5NiBsj0vWP2Q1Zs3jFBWTG?si=JM5GQBWgRjyxreANyqZYcA",
     "https://open.spotify.com/track/5AZ41aRMKszALdu5qm4sju?si=lktFaXpIReecqoZ5zCqKfw",
     "https://open.spotify.com/track/1Prjmg5jgZPHZZtEHSR1A4?si=_x4bCSIkQU-xizMEL4xcQQ",
     "https://open.spotify.com/track/5IhULiOyG58jL20qWkztEg?si=gJn2c_ydSJy8f6MFtIiEmQ",
     "https://open.spotify.com/track/3nmsic2kCWqzDTPHVLXVcn?si=5U_PpHRuTpGG0KlIu9nzuQ",
     "https://open.spotify.com/track/6T03CN5UVnCGPz3muqvpOz?si=2N3c0cl5Q0aPMXdTpXNknQ",
     "https://open.spotify.com/track/0b3AWnucbSBd75GzZQSXPA?si=GJCmngY4Taybl16sMxAuCw",
     "https://open.spotify.com/track/4zbeozbK1z1OM8p8EzG310?si=Ff1VZfCGTvytCNq8OIdyCw",
     "https://open.spotify.com/track/4mkqoe1yptnwU5S537fYlT?si=X4rUTO2iRqOiQp8k36-s0A",
     "https://open.spotify.com/track/1ZK1o0f4Wr7d3o9qZDBxr5?si=F6EmgL1BTOqM4OktRNQRcA",
     "https://open.spotify.com/track/6bnCgtR9tDcADREMONA91t?si=SB5kptOWQUm02IEfPuO1hQ",
     "https://open.spotify.com/track/4iINzr6KLqOzwvcCN915S2?si=AfkMf6UzQgKJQzKXK9EMrg",
     "https://open.spotify.com/track/5MxlCCea2uHpVk8t8n8sj3?si=-UvZJrCaS7W82fVYOzA70Q",
     "https://open.spotify.com/track/25RJ8ELZpDxxqYewIesAXY?si=rRNh3JnnT2qzNv9Dg5MSKA",
     "https://open.spotify.com/track/7oT80u93j4B5HSs2GBpT2S?si=rvsqH7wLRXmeIpIeZ9rsww",
     "https://open.spotify.com/track/6odjb0tn9wgrMbd7dvzcdL?si=kDCFncxYQoyk-rSCr6j0MQ",
     "https://open.spotify.com/track/528jcoA4DKyxBAHlmCU8je?si=Bbh-Xss_QxiCDGIU51LVOg",
     "https://open.spotify.com/track/6xbi77Vq9RALnKc59kSXIS?si=Y8K7Q5wPTNaZ6nbMJf-z-Q",
     "https://open.spotify.com/track/4cdLiwrmpSlke1IyjBWGJR?si=_t3ljtYUTC6msl0o_3x0bQ",
     'https://open.spotify.com/track/38JRCDnXTA9XG58jJnhh6l?si=TCMX9TEbRtCa-NRRtylXBg',
    ], 
   }
  }
 }
}

/*const separatedSong = songList.map(song => {
 const [artist, title] = song.split(' - ');
 return { artist, title };
});*/